scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "delivery_service"
    static_configs:
      - targets: ['host.docker.internal:8000']

rule_files:
  - /etc/prometheus/alert_rules.yml 